# Generated by Django 4.1.6 on 2023-02-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_rename_pets_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="age",
            field=models.IntegerField(),
        ),
    ]
